model_api="https://api.deepseek.com"
model_key="YOUR-KEY"
model_name="deepseek-chat"
[connections.postgresql]
dialect = "postgresql"
host = "DATABASE-HOST"
port = "PORT"
database = "DATABASE-NAME"
username = "DATABASE-ADMIN"
password = "DATABASE-SECRET"